# Generated by Django 3.0.2 on 2020-01-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('CP', models.CharField(max_length=150, verbose_name='Процессор')),
                ('OZU', models.PositiveIntegerField(help_text='(Объем)', verbose_name='ОЗУ')),
                ('memory', models.PositiveIntegerField(help_text='(Объем)', verbose_name='ПЗУ')),
                ('battery', models.PositiveIntegerField(help_text='mAh', verbose_name='Батарея')),
                ('display', models.CharField(max_length=200, verbose_name='Экран')),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('display', models.CharField(max_length=200, verbose_name='Экран')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('baseproductmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.BaseProductModel')),
                ('CP', models.CharField(max_length=150, verbose_name='Процессор')),
                ('OZU', models.PositiveIntegerField(help_text='(Объем)', verbose_name='ОЗУ')),
                ('memory', models.PositiveIntegerField(help_text='(Объем)', verbose_name='ПЗУ')),
                ('video_card', models.CharField(max_length=200, verbose_name='Видеокарта')),
                ('power_block', models.CharField(max_length=200, verbose_name='Блок питания')),
                ('mother_bord', models.CharField(max_length=200, verbose_name='Материнская плата')),
            ],
            bases=('products.baseproductmodel',),
        ),
    ]
